imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# Monitor health check config
services:
    monitor.check.redis:
        class: Tvision\MonitorBundle\Check\RedisCheck
        arguments: ["%cache_default_host%", "%cache_default_port%"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.cms.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["www.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.book.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["book.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.lup.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["lup.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.goe.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["goe.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.jig.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["jig.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.lav.terravision:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["lav.terravision.eu"]
        tags:
          - { name: liip_monitor.check }

    # Lowcost Parking HTTP Checks
    monitor.check.cms.lowcostparking:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["www.lowcostparking.eu"]
        tags:
          - { name: liip_monitor.check }

    monitor.check.book.lowcostparking:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["book.lowcostparking.eu"]
        tags:
          - { name: liip_monitor.check }

    # Terracafe HTTP check
    monitor.check.cms.terracafe:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["www.terracafe.eu"]
        tags:
          - { name: liip_monitor.check }

    # Terravision Travel HTTP check
    monitor.check.cms.terravisiontravel:
        class: Tvision\MonitorBundle\Check\HostCheck
        arguments: ["www.terravisiontravel.com"]
        tags:
          - { name: liip_monitor.check }
